create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  tracking_number text,
  customer_name text,
  customer_email text,
  customer_phone text,
  address text,
  city text,
  country text,
  payment_method text,
  currency text not null default 'USD',
  subtotal numeric not null default 0,
  shipping numeric not null default 0,
  total numeric not null default 0,
  notes text,
  items jsonb not null default '[]'::jsonb,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists tracking_number text;

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_tracking_number_idx on public.orders (tracking_number);
