export const phoneModelsByBrand = {
  Apple: [
    "iPhone SE (2nd Gen)",
    "iPhone 12 mini",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13 mini",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 15",
    "iPhone 15 Plus",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone 16",
    "iPhone 16 Plus",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",
  ],
  Samsung: [
    "Galaxy S21",
    "Galaxy S21+",
    "Galaxy S21 Ultra",
    "Galaxy S21 FE",
    "Galaxy S22",
    "Galaxy S22+",
    "Galaxy S22 Ultra",
    "Galaxy S23",
    "Galaxy S23+",
    "Galaxy S23 Ultra",
    "Galaxy S23 FE",
    "Galaxy S24",
    "Galaxy S24+",
    "Galaxy S24 Ultra",
    "Galaxy S24 FE",
    "Galaxy A14",
    "Galaxy A15",
    "Galaxy A24",
    "Galaxy A25",
    "Galaxy A34",
    "Galaxy A35",
    "Galaxy A54",
    "Galaxy A55",
    "Galaxy A56",
    "Galaxy Z Fold2",
    "Galaxy Z Fold3",
    "Galaxy Z Fold4",
    "Galaxy Z Fold5",
    "Galaxy Z Fold6",
    "Galaxy Z Flip3",
    "Galaxy Z Flip4",
    "Galaxy Z Flip5",
    "Galaxy Z Flip6",
  ],
  Google: [
    "Pixel 5",
    "Pixel 5a",
    "Pixel 6",
    "Pixel 6 Pro",
    "Pixel 6a",
    "Pixel 7",
    "Pixel 7 Pro",
    "Pixel 7a",
    "Pixel 8",
    "Pixel 8 Pro",
    "Pixel 8a",
    "Pixel 9",
    "Pixel 9 Pro",
    "Pixel 9 Pro XL",
    "Pixel 9 Pro Fold",
    "Pixel Fold",
  ],
  Xiaomi: [
    "Redmi 12",
    "Redmi 13C",
    "Redmi Note 12",
    "Redmi Note 12 Pro",
    "Redmi Note 13",
    "Redmi Note 13 Pro",
    "Redmi Note 13 Pro+",
    "Xiaomi 13",
    "Xiaomi 13 Pro",
    "Xiaomi 13T",
    "Xiaomi 14",
    "Xiaomi 14 Ultra",
    "Xiaomi 14T",
    "Xiaomi 14T Pro",
    "Poco X6",
    "Poco X6 Pro",
    "Poco F6",
    "Poco F6 Pro",
  ],
  OnePlus: [
    "OnePlus 9",
    "OnePlus 9 Pro",
    "OnePlus 10 Pro",
    "OnePlus 10T",
    "OnePlus 11",
    "OnePlus 11R",
    "OnePlus 12",
    "OnePlus 12R",
    "OnePlus Open",
    "OnePlus Nord CE 3 Lite",
    "OnePlus Nord 3",
    "OnePlus Nord CE 4",
    "OnePlus Nord 4",
  ],
  Tecno: [
    "Camon 17",
    "Camon 18",
    "Camon 19",
    "Camon 20",
    "Camon 30",
    "Phantom X",
    "Phantom V Fold",
    "Spark 8",
    "Spark 10 Pro",
    "Spark 20",
    "Pova 5",
    "Pova 6",
  ],
  Infinix: [
    "Note 10 Pro",
    "Note 11",
    "Note 12",
    "Note 30 Pro",
    "Note 40 Pro",
    "Zero 8",
    "Zero 20",
    "Zero 30",
    "Hot 12",
    "Hot 20",
    "Hot 40 Pro",
  ],
};

export const nonPhoneModelsByBrand = {
  Apple: {
    Laptops: ["MacBook Air M1", "MacBook Air M2", "MacBook Air M3", "MacBook Pro 14", "MacBook Pro 16"],
    Tablets: ["iPad 10th Gen", "iPad Air (5th Gen)", "iPad Pro 11", "iPad Pro 13", "iPad mini (6th Gen)"],
    Wearables: ["Apple Watch SE (2nd Gen)", "Apple Watch Series 8", "Apple Watch Series 9", "Apple Watch Ultra 2"],
    Audio: ["AirPods (3rd Gen)", "AirPods Pro (2nd Gen)", "AirPods Max"],
    Accessories: [
      "Apple 20W USB-C Power Adapter",
      "MagSafe Charger",
      "Magic Keyboard",
      "Magic Mouse",
      "Apple Pencil (2nd Gen)",
      "Apple Pencil Pro",
    ],
  },
  Samsung: {
    Laptops: ["Galaxy Book3 Pro", "Galaxy Book3 Ultra", "Galaxy Book4 Pro", "Galaxy Book4 Ultra"],
    Tablets: [
      "Galaxy Tab A9+",
      "Galaxy Tab S9 FE",
      "Galaxy Tab S9",
      "Galaxy Tab S9+",
      "Galaxy Tab S9 Ultra",
      "Galaxy Tab S10+",
      "Galaxy Tab S10 Ultra",
    ],
    Wearables: ["Galaxy Watch6", "Galaxy Watch6 Classic", "Galaxy Watch7", "Galaxy Watch Ultra", "Galaxy Ring"],
    Audio: ["Galaxy Buds FE", "Galaxy Buds2 Pro", "Galaxy Buds3", "Galaxy Buds3 Pro"],
    Accessories: [
      "25W Power Adapter",
      "45W Power Adapter",
      "15W Wireless Charger Duo",
      "S Pen Creator Edition",
      "SmartTag2",
    ],
  },
  Google: {
    Tablets: ["Pixel Tablet"],
    Wearables: ["Pixel Watch 2", "Pixel Watch 3"],
    Audio: ["Pixel Buds A-Series", "Pixel Buds Pro", "Pixel Buds Pro 2"],
    Accessories: ["30W USB-C Charger", "Pixel Stand (2nd Gen)", "Nest Wifi Pro"],
    "Smart Home": ["Nest Hub (2nd Gen)", "Nest Hub Max", "Nest Audio", "Nest Mini"],
  },
  Xiaomi: {
    Tablets: ["Redmi Pad SE", "Xiaomi Pad 6", "Xiaomi Pad 6S Pro"],
    Wearables: ["Xiaomi Watch S3", "Redmi Watch 4", "Smart Band 8"],
    Audio: ["Redmi Buds 4 Pro", "Xiaomi Buds 5"],
    "Smart Home": ["Xiaomi Smart Camera C300", "Mi Smart Home Hub"],
  },
  OnePlus: {
    Tablets: ["OnePlus Pad", "OnePlus Pad 2"],
    Wearables: ["OnePlus Watch 2"],
    Audio: ["OnePlus Buds Pro 2", "OnePlus Buds 3"],
    Accessories: ["SUPERVOOC 100W Charger"],
  },
  Dell: {
    Laptops: ["XPS 13", "XPS 15", "XPS 16", "Alienware m16", "Alienware x16", "Inspiron 15"],
    Accessories: ["Dell Pro Wireless Mouse MS5120W", "Dell USB-C Mobile Adapter DA310", "Dell EcoLoop Pro Backpack"],
  },
  HP: {
    Laptops: ["Spectre x360 14", "Envy x360 16", "Omen 16", "Victus 15", "Pavilion Plus 14"],
    Accessories: ["HP 930 Creator Wireless Mouse", "HP USB-C Travel Hub G2"],
  },
  Lenovo: {
    Laptops: ["ThinkPad X1 Carbon Gen 11", "Yoga 9i", "Legion Pro 5", "Legion Pro 7", "IdeaPad Slim 5"],
    Tablets: ["Tab P11 Pro Gen 2", "Tab P12", "Tab Extreme"],
    Accessories: ["ThinkPad Universal USB-C Dock", "Lenovo Go Wireless Multi-Device Mouse"],
  },
  Asus: {
    Laptops: [
      "Zenbook 14 OLED",
      "Zenbook Duo",
      "ROG Zephyrus G14",
      "ROG Zephyrus G16",
      "ROG Strix SCAR 18",
      "Vivobook S 15",
    ],
    Accessories: ["ROG Harpe Ace Aim Lab Edition", "Asus 100W 3-Port GaN Charger"],
  },
  Tecno: {
    Tablets: ["MegaPad 10"],
    Audio: ["Sonic 1 Earbuds"],
    Accessories: ["Fast Charger 45W"],
  },
  Infinix: {
    Tablets: ["XPAD"],
    Audio: ["XE23 Earbuds"],
    Accessories: ["Fast Charge Adapter 45W"],
  },
};
