export const products = [
  {
    id: "iphone-13-used",
    name: "iPhone 13",
    condition: "Used - Excellent",
    category: "Phones",
    basePriceUsd: 520,
    details: "128GB, battery health 89%, unlocked and fully tested.",
  },
  {
    id: "s24-new",
    name: "Samsung Galaxy S24",
    condition: "New",
    category: "Phones",
    basePriceUsd: 760,
    details: "Factory sealed, dual SIM, one-year manufacturer warranty.",
  },
  {
    id: "xps13-used",
    name: "Dell XPS 13",
    condition: "Used - Very Good",
    category: "Laptops",
    basePriceUsd: 680,
    details: "Core i7, 16GB RAM, 512GB SSD, fresh OS install included.",
  },
  {
    id: "airpods-pro-new",
    name: "AirPods Pro (2nd Gen)",
    condition: "New",
    category: "Accessories",
    basePriceUsd: 210,
    details: "Original package with active noise cancellation support.",
  },
  {
    id: "ps5-used",
    name: "PlayStation 5",
    condition: "Used - Excellent",
    category: "Gaming",
    basePriceUsd: 440,
    details: "Includes one controller, HDMI cable, and power cable.",
  },
  {
    id: "watch-9-new",
    name: "Apple Watch Series 9",
    condition: "New",
    category: "Wearables",
    basePriceUsd: 350,
    details: "45mm GPS model with original charger and strap.",
  },
];
