export const CV_RESUME_LINES = [
  { style: "title", text: "Chinedu David Nwadialo" },
  { style: "subtitle", text: "Full Stack Developer" },
  { style: "meta", text: "itssirdavid@gmail.com | +2347041342391 | Lagos, Nigeria" },
  { style: "meta", text: "github.com/sirdavid001 | sirdavid.site" },
  { style: "spacer" },
  { style: "section", text: "PROFESSIONAL SUMMARY" },
  {
    style: "body",
    text: "Full Stack Web Developer with a focus on building responsive, production-ready web applications.",
  },
  {
    style: "body",
    text: "Experienced in creating clean, user-friendly interfaces while ensuring backend systems are reliable and efficient.",
  },
  {
    style: "body",
    text: "Proficient in transforming product requirements into secure, maintainable, and deployment-ready solutions.",
  },
  {
    style: "body",
    text: "Particularly interested in projects involving role-based access control, database-driven content, payment systems, and admin dashboards.",
  },
  {
    style: "body",
    text: "Passionate about growing into a senior web engineer with full ownership from conception to deployment.",
  },
  { style: "spacer" },
  { style: "section", text: "EDUCATION" },
  { style: "subheading", text: "Bachelor of Science in Computer Science" },
  { style: "body", text: "Dennis Osadebay University" },
  { style: "body", text: "2021 - 2025" },
  { style: "spacer" },
  { style: "subheading", text: "Senior Secondary School Certificate" },
  { style: "body", text: "Redeemers International High School Asaba" },
  { style: "body", text: "2014 - 2019" },
  { style: "body", text: "Asaba, Delta State, Nigeria" },
  {
    style: "body",
    text: "West African Examinations Council (WAEC) - SSCE certificate",
  },
  {
    style: "body",
    text: "National Examinations Council (NECO) - SSCE certificate",
  },
  { style: "body", text: "Junior WAEC (BECE/JSS3 result)" },
  { style: "spacer" },
  { style: "subheading", text: "Primary School Leaving Certificate" },
  { style: "body", text: "Jasmine Children School" },
  { style: "body", text: "2010 - 2013" },
  { style: "body", text: "Asaba, Delta State, Nigeria" },
  { style: "spacer" },
  { style: "section", text: "PROJECTS" },
  { style: "subheading", text: "MY-PORTFOLIO" },
  { style: "body", text: "Technologies: React, JavaScript, Vite, Tailwind CSS, Node.js, Supabase, Paystack, Resend" },
  { style: "body", text: "Period: Feb - Mar 2025" },
  {
    style: "body",
    text: "Built a full-stack portfolio/shop web application with complete checkout and admin management flow.",
  },
  { style: "bullet", text: "Implemented secure payment integration with Paystack including webhook verification." },
  { style: "bullet", text: "Integrated Resend email notifications for order confirmations and updates." },
  { style: "bullet", text: "Developed admin dashboard for product, shipping, and order management." },
  { style: "bullet", text: "Configured deployment-ready setup with Vercel and environment-driven integrations." },
  { style: "spacer" },
  { style: "subheading", text: "online-exam-system" },
  {
    style: "body",
    text: "Technologies: Python, Django, PostgreSQL, JavaScript, HTML/CSS, Gunicorn, WhiteNoise",
  },
  { style: "body", text: "Period: Aug 2025 - Feb 2026" },
  {
    style: "body",
    text: "Developed a role-based online examination platform for admins, teachers, and students.",
  },
  { style: "bullet", text: "Built course, question, and timed exam management with shuffle and attempt limits." },
  { style: "bullet", text: "Implemented automated scoring with negative marking and detailed result tracking." },
  { style: "bullet", text: "Created admin workflows for user onboarding, approvals, announcements, and dashboards." },
  { style: "bullet", text: "Added report exports in CSV and Excel formats." },
  { style: "spacer" },
  { style: "subheading", text: "uKnowMe" },
  { style: "body", text: "Technologies: React, JavaScript, HTML/CSS" },
  { style: "body", text: "Period: 2025 - 2026" },
  { style: "bullet", text: "Built a clean, user-focused web experience for identity and profile storytelling." },
  { style: "bullet", text: "Designed responsive UI/UX for consistent experience across devices." },
  { style: "bullet", text: "Delivered a production-ready deployment showcase of frontend capabilities." },
  { style: "spacer" },
  { style: "section", text: "TECHNICAL SKILLS" },
  { style: "subheading", text: "Programming Languages" },
  { style: "body", text: "JavaScript, TypeScript, Python, SQL, HTML, CSS" },
  { style: "subheading", text: "Frontend Frameworks & Libraries" },
  { style: "body", text: "React, React Native (Expo), Next.js, Vite, Tailwind CSS" },
  { style: "subheading", text: "Backend Frameworks & Tools" },
  { style: "body", text: "Django, Node.js, Fastify, Express, Gunicorn, WhiteNoise" },
  { style: "subheading", text: "Databases & ORMs" },
  { style: "body", text: "PostgreSQL, SQLite, Supabase, Prisma ORM" },
  { style: "subheading", text: "Development Tools" },
  { style: "body", text: "Git, GitHub, npm, Docker, Vercel, Render, CI/CD" },
  { style: "subheading", text: "API & Integration" },
  { style: "body", text: "REST API, JWT/Session Auth, Webhooks, AWS SDK (S3), Zod, Ethers.js" },
  { style: "spacer" },
  { style: "body", text: "References available upon request." },
];
